# Generated by Django 3.0.6 on 2020-06-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0002_task_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(default='noImg.jpg', upload_to='images/'),
        ),
    ]
